#!/bin/tcsh -f

if ( -e /Library/Frameworks/Keychain.framework ) then
	rm -R /Library/Frameworks/Keychain.framework
endif

if ( -e build/Debug/Keychain.framework ) then
	cp -R build/Debug/Keychain.framework /Library/Frameworks/
else if ( -e build/Release/Keychain.framework ) then
	cp -R build/Release/Keychain.framework /Library/Frameworks/
else
	echo "No built products found."
endif
